# Generated by Django 2.2.6 on 2019-10-31 18:37

from django.db import migrations, models
import django.db.models.deletion
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('desc', models.CharField(max_length=1024, null=True, verbose_name='Description')),
                ('datasheet', models.CharField(max_length=2048, null=True, verbose_name='Datasheet')),
                ('code', models.CharField(max_length=256, null=True, verbose_name='Code')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Price')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('dt_created', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('dt_modif', models.DateField(auto_now=True, verbose_name='Change date')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('desc', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, verbose_name='Rating')),
                ('comment', models.CharField(blank=True, max_length=512, null=True, verbose_name='Comment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='item.Item')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='userprofile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_img', models.ImageField(default='notfound.png', upload_to=item.models.item_directory_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='item.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(null=True, related_name='items', to='item.ItemCategory'),
        ),
    ]
