# Generated by Django 2.2.6 on 2019-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='items', to='item.ItemCategory'),
        ),
    ]
